version: '3.9'

services:
  app:
    build: .
    env_file:
      - .env.enc
    scale: 10
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - 3001:3001