version: '3.9'

services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    env_file:
      - .env
    ports:
      - 5173:5173
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    deploy:
      replicas: 10

  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf   # Add this line
    depends_on:
      - app
    ports:
      - 8080:8080

